import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"RadhaXChatGpt_Bot") 
SUDO=os.environ.get("SUDO","6039423699")
BOT_NAME = os.environ.get("BOT_NAME","CHATGPT BOT")
START_IMG = os.environ.get("START_IMG","https://graph.org/file/5eddb24742645c4c7e192.jpg")
STKR = os.environ.get("STKR","CAACAgIAAxkBAAEDAi9kpoZsScowUfZL9z6RC-NFzkR4swACFzMAAllsMEkhLDB782R9GS8E")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","RadhaX2Update")
# OWNER_USERNAME = os.environ.get("OWNER_USERNAME","MissRadha")
SUDO=os.environ.get("SUDO","6039423699")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","RadhaX2Support")
